# Generated by Django 3.2.6 on 2023-01-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230105_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='receivingitem',
            name='name',
        ),
    ]
