# Generated by Django 3.2.6 on 2023-01-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230105_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiving',
            name='totalPrice',
        ),
    ]
